POST http://127.0.0.1:8080/account HTTP/2
Content-Type: application/json

{
  "name": "saipos",
  "login": "pedrinhosilvayoshimura@gmail.com",
  "password": "RG@alp28"
}

###
GET http://127.0.0.1:8080/account/saipos HTTP/2
Content-Type: application/json